const BlogData=[
    {
      id:1,
      date:"January 10,2024",
      category:"Content writing",
      title:"Investment Planning",
      cover:"/images/single-1.jpg",
      para:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
      desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
    },
    {
        id:2,
        date:"January 10,2024",
        category:"Business",
        title:"Investment Planning",
        cover:"/images/single-2.jpg",
        para:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
        desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
      },
      {
        id:3,
        date:"January 10,2024",
        category:"Travelling",
        title:"Investment Planning",
        cover:"/images/blog-1.jpg",
        para:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
        desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
      },
      {
        id:4,
        date:"January 10,2024",
        category:"Developement",
        title:"Investment Planning",
        cover:"/images/blog-2.jpg",
        para:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
        desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
      },
      {
        id:5,
        date:"January 10,2024",
        category:"Motion Designer",
        title:"Investment Planning",
        cover:"/images/blog-3.jpg",
        para:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
        desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
      },
      {
        id:6,
        date:"January 10,2024",
        category:"Web Developement",
        title:"Investment Planning",
        cover:"/images/blog-4.jpg",
        para:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
        desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
      },
      {
        id:7,
        date:"January 10,2024",
        category:"Business Strategy",
        title:"Investment Planning",
        cover:"/images/blog-5.jpg",
        para:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
        desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
      },
      {
        id:8,
        date:"January 10,2024",
        category:"Content writing",
        title:"Investment Planning",
        cover:"/images/blog-6.jpg",
        para:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
        desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis mollitia error earum, dolor odio provident libero repellendus cupiditate unde perspiciatis harum iure similique esse, facilis voluptatem saepe, iusto maxime ex!",
      },
]
export default BlogData